-- VISTAS
/* DATOS CLIENTES_GENERAL */
CREATE VIEW VST_CLIENTE_GENERAL AS
SELECT CEDULA, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION 
FROM TBL_CLIENTES;

/* AGREGAR CLIENTE BASE*/
CREATE OR REPLACE PROCEDURE SP_AGREGAR_CLIENTE_BASE (
        CEDULA IN VARCHAR2,
	PRIMER_NOMBRE IN VARCHAR2,
	SEGUNDO_NOMBRE IN VARCHAR2,
	PRIMER_APELLIDO IN VARCHAR2,
	SEGUNDO_APELLIDO IN VARCHAR2,
	DIRECCION IN VARCHAR2,
        MSJ_SALIDA OUT VARCHAR2
)
AS
    --
BEGIN
    -- INSERTAR CLIENTE
	INSERT INTO TBL_CLIENTES
	VALUES (CEDULA, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, DIRECCION);
	-- INSERTAR TELEFONO
	COMMIT;
	-- MENSAJE SALIDA
	MSJ_SALIDA := 'Cliente agregado exitosamente.';
EXCEPTION
    -- Capturar cualquier excepción y enviar mensaje de error
	WHEN OTHERS THEN
		MSJ_SALIDA := 'Cliente no agregado debido a la falla: ' || SQLCODE || '-' || SQLERRM || '.';
END;
/

/* EDITAR CLIENTE BASE*/
create or replace PROCEDURE SP_EDITAR_CLIENTE_BASE (
        CED IN VARCHAR2,
	NOMBRE1 IN VARCHAR2,
	NOMBRE2 IN VARCHAR2,
	APELLIDO1 IN VARCHAR2,
	APELLIDO2 IN VARCHAR2,
	DIR IN VARCHAR2,
        MSJ_SALIDA OUT VARCHAR2
)
AS
    --
BEGIN
    -- ACTUALIZAR CLIENTE
        UPDATE "TBL_CLIENTES" SET 
            PRIMER_NOMBRE = NOMBRE1, 
            SEGUNDO_NOMBRE = NOMBRE2, 
            PRIMER_APELLIDO = APELLIDO1, 
            SEGUNDO_APELLIDO = APELLIDO2, 
            DIRECCION =  DIR
        WHERE 
            CEDULA = CED;

        --- ACTUALIZAR
        COMMIT;
        --- MENSAJE SALIDA
        MSJ_SALIDA := 'Editado exitosamente.';
        EXCEPTION
        ---mensaje de error en caso de error
        WHEN OTHERS THEN
            MSJ_SALIDA := 'Error '|| SQLCODE || '-' || SQLERRM || '.';
END;

/* BORRAR CLIENTE BASE*/
create or replace PROCEDURE SP_BORRAR_CLIENTE_BASE (
        CED IN VARCHAR2,
        MSJ_SALIDA OUT VARCHAR2
)
AS
    --
BEGIN
    -- ACTUALIZAR CLIENTE
        DELETE FROM "TBL_CLIENTES"
        WHERE CEDULA =CED;
        --- ELIMINA
        COMMIT;
        --- MENSAJE SALIDA
        MSJ_SALIDA := 'Editado exitosamente.';
        EXCEPTION
        ---mensaje de error en caso de error
        WHEN OTHERS THEN
            MSJ_SALIDA := 'Error '|| SQLCODE || '-' || SQLERRM || '.';
END;
